version: '3'
services:
  app:
    image: film-nexus
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FACEBOOK_REDIRECT_URL: ${FACEBOOK_REDIRECT_URL}
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: filmnexus
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./server/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - '5432:5432'
    depends_on:
      - redis
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
