version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: filmnexus
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
