# fly.toml app configuration file generated for black-dust-442 on 2023-08-10T23:00:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-dust-442"
primary_region = "lax"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
